### ISSUE TITLE
No events for files created inside `temp`

### ISSUE THREAD

**Issue by mkhl** [Axosoft/nsfw#7]
[This patch](https://gist.github.com/mkhl/e4b299efb7777104a816a4f313438025) modifies the spec to create files inside a temporary directory created with [`temp`](https://www.npmjs.com/package/temp).

As a result, all tests fail with timeouts (after about 240000ms).

Tested against 1.0.12 (d466bd1cc448e0fad58ff7ea5789c3e25927056f) on OS X:

    ProductName:	Mac OS X
    ProductVersion:	10.11.4
    BuildVersion:	15E65

**Comment by implausible** [comment]
@mkhl Will take a look at this next time I'm on my Mac.

**Comment by implausible** [comment]
In fact, I think I could probably patch this by using fs.realpath. Thanks for bringing this to my attention.

**Comment by implausible** [comment]
So, tried to run your patch. Received failures on every test, spent some time trying to find out what was wrong. At the very least, the patch you provided is inaccurate and will not work because you are calling `temp.mkdir('mockfs')` which is an async function that returns undefined. So you're entire test strategy was to perform operations on basically garbage. After correcting that in the test cases, it seems to be a non-issue.

What I would suggest doing is using `fs.realpathSync(temp.mkdirSync('your_temp_folder'))` to get your actual path. If you're comfortable, try using async code instead.

**Comment by mkhl** [comment]
Hm, interesting.

Thank you for checking it out and sorry for the noise.
